// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5OCdnxJmNIlQgdYpTQ5MzuLW6w7w4gOk',
    appId: '1:238999938830:web:d0b4026540abd47fd2195f',
    messagingSenderId: '238999938830',
    projectId: 'crossplatform-a6e19',
    authDomain: 'crossplatform-a6e19.firebaseapp.com',
    databaseURL: 'https://crossplatform-a6e19-default-rtdb.firebaseio.com',
    storageBucket: 'crossplatform-a6e19.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdZ07eEtAQ7qspH65uDRA2o7dmPu1XH-E',
    appId: '1:238999938830:android:888e9225ee75f105d2195f',
    messagingSenderId: '238999938830',
    projectId: 'crossplatform-a6e19',
    databaseURL: 'https://crossplatform-a6e19-default-rtdb.firebaseio.com',
    storageBucket: 'crossplatform-a6e19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1vX2_3CtUbubPtrnIZiqskRmumS4pfVY',
    appId: '1:238999938830:ios:8c4197c4a1f8d22ad2195f',
    messagingSenderId: '238999938830',
    projectId: 'crossplatform-a6e19',
    databaseURL: 'https://crossplatform-a6e19-default-rtdb.firebaseio.com',
    storageBucket: 'crossplatform-a6e19.firebasestorage.app',
    iosBundleId: 'com.example.market',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1vX2_3CtUbubPtrnIZiqskRmumS4pfVY',
    appId: '1:238999938830:ios:8c4197c4a1f8d22ad2195f',
    messagingSenderId: '238999938830',
    projectId: 'crossplatform-a6e19',
    databaseURL: 'https://crossplatform-a6e19-default-rtdb.firebaseio.com',
    storageBucket: 'crossplatform-a6e19.firebasestorage.app',
    iosBundleId: 'com.example.market',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5OCdnxJmNIlQgdYpTQ5MzuLW6w7w4gOk',
    appId: '1:238999938830:web:32de3aabab20c2d5d2195f',
    messagingSenderId: '238999938830',
    projectId: 'crossplatform-a6e19',
    authDomain: 'crossplatform-a6e19.firebaseapp.com',
    databaseURL: 'https://crossplatform-a6e19-default-rtdb.firebaseio.com',
    storageBucket: 'crossplatform-a6e19.firebasestorage.app',
  );
}
